const actionTypes = {

	// Login
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	LOGIN_PENDING: 'LOGIN_PENDING',
	LOGIN_ERROR: 'LOGIN_ERROR',

	// Logout
	LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
	LOGOUT_PENDING: 'LOGOUT_PENDING',
	LOGOUT_ERROR: 'LOGOUT_ERROR',

	// Register
	REGISTER_SUCCESS: 'REGISTER_SUCCESS',
	REGISTER_PENDING: 'REGISTER_PENDING',
	REGISTER_ERROR: 'REGISTER_ERROR',

	// Get User
	GET_USER_SUCCESS: 'GET_USER_SUCCESS',
	GET_USER_PENDING: 'GET_USER_PENDING',
	GET_USER_ERROR: 'GET_USER_ERROR'

}

export default actionTypes
