const actionTypes = {

	// Login
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	LOGIN_PENDING: 'LOGIN_PENDING',
	LOGIN_ERROR: 'LOGIN_ERROR',

	// Logout
	LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
	LOGOUT_PENDING: 'LOGOUT_PENDING',
	LOGOUT_ERROR: 'LOGOUT_ERROR',

	// Register
	REGISTER_SUCCESS: 'REGISTER_SUCCESS',
	REGISTER_PENDING: 'REGISTER_PENDING',
	REGISTER_ERROR: 'REGISTER_ERROR',

	// Testimonial
	GET_TESTIMONIAL_SUCCESS: 'GET_TESTIMONIAL_SUCCESS',
	GET_TESTIMONIAL_PENDING: 'GET_TESTIMONIAL_PENDING',
	GET_TESTIMONIAL_ERROR: 'GET_TESTIMONIAL_ERROR',

	CREATE_TESTIMONIAL_SUCCESS: 'CREATE_TESTIMONIAL_SUCCESS',
	CREATE_TESTIMONIAL_PENDING: 'CREATE_TESTIMONIAL_PENDING',
	CREATE_TESTIMONIAL_ERROR: 'CREATE_TESTIMONIAL_ERROR',

	// Profile
	GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',
	GET_PROFILE_PENDING: 'GET_PROFILE_PENDING',
	GET_PROFILE_ERROR: 'GET_PROFILE_ERROR',

	SET_PROFILE_SUCCESS: 'SET_PROFILE_SUCCESS',
	SET_PROFILE_PENDING: 'SET_PROFILE_PENDING',
	SET_PROFILE_ERROR: 'SET_PROFILE_ERROR',

	// User
	GET_USER_SUCCESS: 'GET_USER_SUCCESS',
	GET_USER_PENDING: 'GET_USER_PENDING',
	GET_USER_ERROR: 'GET_USER_ERROR'

}

export default actionTypes
